baseurl = "/"
languageCode = "en-us"
title = "Abnormal Distributions"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3
[[menu.main]]
    name = "Articles"
    url = "/categories/"
    weight = 4


[params]
    description = "A website built through Hugo and blogdown."
    footer = "[Github](https://github.com/dannymorris) | [LinkedIn](https://www.linkedin.com/in/drmorris87/) | [Email](mailto:drmorris87@outlook.com)"
